# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from naql.v1 import services_pb2 as naql_dot_v1_dot_services__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in naql/v1/services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub(object):
    """============================================================
    Identity Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/naql.v1.IdentityService/Register',
                request_serializer=naql_dot_v1_dot_services__pb2.RegisterRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/naql.v1.IdentityService/Login',
                request_serializer=naql_dot_v1_dot_services__pb2.LoginRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/naql.v1.IdentityService/RefreshToken',
                request_serializer=naql_dot_v1_dot_services__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/naql.v1.IdentityService/GetUser',
                request_serializer=naql_dot_v1_dot_services__pb2.GetUserRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserDetails = channel.unary_unary(
                '/naql.v1.IdentityService/GetUserDetails',
                request_serializer=naql_dot_v1_dot_services__pb2.GetUserRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/naql.v1.IdentityService/UpdateUser',
                request_serializer=naql_dot_v1_dot_services__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.UserResponse.FromString,
                _registered_method=True)
        self.VerifyKYC = channel.unary_unary(
                '/naql.v1.IdentityService/VerifyKYC',
                request_serializer=naql_dot_v1_dot_services__pb2.VerifyKYCRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/naql.v1.IdentityService/ListUsers',
                request_serializer=naql_dot_v1_dot_services__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ListUsersResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer(object):
    """============================================================
    Identity Service
    ============================================================

    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyKYC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=naql_dot_v1_dot_services__pb2.RegisterRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=naql_dot_v1_dot_services__pb2.LoginRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=naql_dot_v1_dot_services__pb2.RefreshTokenRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.LoginResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetUserRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.UserResponse.SerializeToString,
            ),
            'GetUserDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDetails,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetUserRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=naql_dot_v1_dot_services__pb2.UpdateUserRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.UserResponse.SerializeToString,
            ),
            'VerifyKYC': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyKYC,
                    request_deserializer=naql_dot_v1_dot_services__pb2.VerifyKYCRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.UserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ListUsersRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ListUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naql.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naql.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """============================================================
    Identity Service
    ============================================================

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/Register',
            naql_dot_v1_dot_services__pb2.RegisterRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/Login',
            naql_dot_v1_dot_services__pb2.LoginRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/RefreshToken',
            naql_dot_v1_dot_services__pb2.RefreshTokenRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/GetUser',
            naql_dot_v1_dot_services__pb2.GetUserRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/GetUserDetails',
            naql_dot_v1_dot_services__pb2.GetUserRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/UpdateUser',
            naql_dot_v1_dot_services__pb2.UpdateUserRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyKYC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/VerifyKYC',
            naql_dot_v1_dot_services__pb2.VerifyKYCRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.IdentityService/ListUsers',
            naql_dot_v1_dot_services__pb2.ListUsersRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FleetServiceStub(object):
    """============================================================
    Fleet Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTruck = channel.unary_unary(
                '/naql.v1.FleetService/RegisterTruck',
                request_serializer=naql_dot_v1_dot_services__pb2.RegisterTruckRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
                _registered_method=True)
        self.GetTruck = channel.unary_unary(
                '/naql.v1.FleetService/GetTruck',
                request_serializer=naql_dot_v1_dot_services__pb2.GetTruckRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
                _registered_method=True)
        self.GetTruckDetails = channel.unary_unary(
                '/naql.v1.FleetService/GetTruckDetails',
                request_serializer=naql_dot_v1_dot_services__pb2.GetTruckRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
                _registered_method=True)
        self.UpdateTruckStatus = channel.unary_unary(
                '/naql.v1.FleetService/UpdateTruckStatus',
                request_serializer=naql_dot_v1_dot_services__pb2.UpdateTruckStatusRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
                _registered_method=True)
        self.ListTrucks = channel.unary_unary(
                '/naql.v1.FleetService/ListTrucks',
                request_serializer=naql_dot_v1_dot_services__pb2.ListTrucksRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ListTrucksResponse.FromString,
                _registered_method=True)
        self.GetTrucksByOwner = channel.unary_unary(
                '/naql.v1.FleetService/GetTrucksByOwner',
                request_serializer=naql_dot_v1_dot_services__pb2.GetTrucksByOwnerRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ListTrucksResponse.FromString,
                _registered_method=True)
        self.AddMaintenance = channel.unary_unary(
                '/naql.v1.FleetService/AddMaintenance',
                request_serializer=naql_dot_v1_dot_services__pb2.AddMaintenanceRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.MaintenanceResponse.FromString,
                _registered_method=True)
        self.GetMaintenanceHistory = channel.unary_unary(
                '/naql.v1.FleetService/GetMaintenanceHistory',
                request_serializer=naql_dot_v1_dot_services__pb2.GetMaintenanceHistoryRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ListMaintenanceResponse.FromString,
                _registered_method=True)


class FleetServiceServicer(object):
    """============================================================
    Fleet Service
    ============================================================

    """

    def RegisterTruck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTruck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTruckDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTruckStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrucks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrucksByOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMaintenance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaintenanceHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTruck': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTruck,
                    request_deserializer=naql_dot_v1_dot_services__pb2.RegisterTruckRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TruckResponse.SerializeToString,
            ),
            'GetTruck': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTruck,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetTruckRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TruckResponse.SerializeToString,
            ),
            'GetTruckDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTruckDetails,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetTruckRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TruckResponse.SerializeToString,
            ),
            'UpdateTruckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTruckStatus,
                    request_deserializer=naql_dot_v1_dot_services__pb2.UpdateTruckStatusRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TruckResponse.SerializeToString,
            ),
            'ListTrucks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrucks,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ListTrucksRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ListTrucksResponse.SerializeToString,
            ),
            'GetTrucksByOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrucksByOwner,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetTrucksByOwnerRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ListTrucksResponse.SerializeToString,
            ),
            'AddMaintenance': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMaintenance,
                    request_deserializer=naql_dot_v1_dot_services__pb2.AddMaintenanceRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.MaintenanceResponse.SerializeToString,
            ),
            'GetMaintenanceHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaintenanceHistory,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetMaintenanceHistoryRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ListMaintenanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naql.v1.FleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naql.v1.FleetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetService(object):
    """============================================================
    Fleet Service
    ============================================================

    """

    @staticmethod
    def RegisterTruck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/RegisterTruck',
            naql_dot_v1_dot_services__pb2.RegisterTruckRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTruck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/GetTruck',
            naql_dot_v1_dot_services__pb2.GetTruckRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTruckDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/GetTruckDetails',
            naql_dot_v1_dot_services__pb2.GetTruckRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTruckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/UpdateTruckStatus',
            naql_dot_v1_dot_services__pb2.UpdateTruckStatusRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.TruckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrucks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/ListTrucks',
            naql_dot_v1_dot_services__pb2.ListTrucksRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ListTrucksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrucksByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/GetTrucksByOwner',
            naql_dot_v1_dot_services__pb2.GetTrucksByOwnerRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ListTrucksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMaintenance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/AddMaintenance',
            naql_dot_v1_dot_services__pb2.AddMaintenanceRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.MaintenanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMaintenanceHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FleetService/GetMaintenanceHistory',
            naql_dot_v1_dot_services__pb2.GetMaintenanceHistoryRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ListMaintenanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MatchingServiceStub(object):
    """============================================================
    Matching Engine
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestMatch = channel.unary_unary(
                '/naql.v1.MatchingService/RequestMatch',
                request_serializer=naql_dot_v1_dot_services__pb2.MatchRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.GetAvailableTrucks = channel.unary_unary(
                '/naql.v1.MatchingService/GetAvailableTrucks',
                request_serializer=naql_dot_v1_dot_services__pb2.AvailableTrucksRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.AvailableTrucksResponse.FromString,
                _registered_method=True)
        self.RespondToMatch = channel.unary_unary(
                '/naql.v1.MatchingService/RespondToMatch',
                request_serializer=naql_dot_v1_dot_services__pb2.MatchDecisionRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.MatchDecisionResponse.FromString,
                _registered_method=True)
        self.UpdateTruckLocation = channel.unary_unary(
                '/naql.v1.MatchingService/UpdateTruckLocation',
                request_serializer=naql_dot_v1_dot_services__pb2.TruckLocationUpdate.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TruckLocationAck.FromString,
                _registered_method=True)
        self.StreamTruckLocations = channel.stream_stream(
                '/naql.v1.MatchingService/StreamTruckLocations',
                request_serializer=naql_dot_v1_dot_services__pb2.TruckLocationUpdate.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TruckLocationAck.FromString,
                _registered_method=True)


class MatchingServiceServicer(object):
    """============================================================
    Matching Engine
    ============================================================

    """

    def RequestMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableTrucks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondToMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTruckLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTruckLocations(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestMatch,
                    request_deserializer=naql_dot_v1_dot_services__pb2.MatchRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.MatchResponse.SerializeToString,
            ),
            'GetAvailableTrucks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableTrucks,
                    request_deserializer=naql_dot_v1_dot_services__pb2.AvailableTrucksRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.AvailableTrucksResponse.SerializeToString,
            ),
            'RespondToMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondToMatch,
                    request_deserializer=naql_dot_v1_dot_services__pb2.MatchDecisionRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.MatchDecisionResponse.SerializeToString,
            ),
            'UpdateTruckLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTruckLocation,
                    request_deserializer=naql_dot_v1_dot_services__pb2.TruckLocationUpdate.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TruckLocationAck.SerializeToString,
            ),
            'StreamTruckLocations': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTruckLocations,
                    request_deserializer=naql_dot_v1_dot_services__pb2.TruckLocationUpdate.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TruckLocationAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naql.v1.MatchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naql.v1.MatchingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchingService(object):
    """============================================================
    Matching Engine
    ============================================================

    """

    @staticmethod
    def RequestMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.MatchingService/RequestMatch',
            naql_dot_v1_dot_services__pb2.MatchRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableTrucks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.MatchingService/GetAvailableTrucks',
            naql_dot_v1_dot_services__pb2.AvailableTrucksRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.AvailableTrucksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondToMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.MatchingService/RespondToMatch',
            naql_dot_v1_dot_services__pb2.MatchDecisionRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.MatchDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTruckLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.MatchingService/UpdateTruckLocation',
            naql_dot_v1_dot_services__pb2.TruckLocationUpdate.SerializeToString,
            naql_dot_v1_dot_services__pb2.TruckLocationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTruckLocations(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/naql.v1.MatchingService/StreamTruckLocations',
            naql_dot_v1_dot_services__pb2.TruckLocationUpdate.SerializeToString,
            naql_dot_v1_dot_services__pb2.TruckLocationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FinTrackServiceStub(object):
    """============================================================
    FinTrack Service
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQuote = channel.unary_unary(
                '/naql.v1.FinTrackService/CreateQuote',
                request_serializer=naql_dot_v1_dot_services__pb2.CreateQuoteRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.QuoteResponse.FromString,
                _registered_method=True)
        self.CreateEscrow = channel.unary_unary(
                '/naql.v1.FinTrackService/CreateEscrow',
                request_serializer=naql_dot_v1_dot_services__pb2.CreateEscrowRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.EscrowResponse.FromString,
                _registered_method=True)
        self.ReleaseEscrow = channel.unary_unary(
                '/naql.v1.FinTrackService/ReleaseEscrow',
                request_serializer=naql_dot_v1_dot_services__pb2.ReleaseEscrowRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.EscrowResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/naql.v1.FinTrackService/ProcessPayment',
                request_serializer=naql_dot_v1_dot_services__pb2.ProcessPaymentRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/naql.v1.FinTrackService/GetBalance',
                request_serializer=naql_dot_v1_dot_services__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/naql.v1.FinTrackService/GetTransactionHistory',
                request_serializer=naql_dot_v1_dot_services__pb2.TransactionHistoryRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.TransactionHistoryResponse.FromString,
                _registered_method=True)
        self.CreateInvoice = channel.unary_unary(
                '/naql.v1.FinTrackService/CreateInvoice',
                request_serializer=naql_dot_v1_dot_services__pb2.InvoiceRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.InvoiceResponse.FromString,
                _registered_method=True)


class FinTrackServiceServicer(object):
    """============================================================
    FinTrack Service
    ============================================================

    """

    def CreateQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEscrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseEscrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInvoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinTrackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQuote,
                    request_deserializer=naql_dot_v1_dot_services__pb2.CreateQuoteRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.QuoteResponse.SerializeToString,
            ),
            'CreateEscrow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEscrow,
                    request_deserializer=naql_dot_v1_dot_services__pb2.CreateEscrowRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.EscrowResponse.SerializeToString,
            ),
            'ReleaseEscrow': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseEscrow,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ReleaseEscrowRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.EscrowResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ProcessPaymentRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.PaymentResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetBalanceRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.BalanceResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=naql_dot_v1_dot_services__pb2.TransactionHistoryRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.TransactionHistoryResponse.SerializeToString,
            ),
            'CreateInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInvoice,
                    request_deserializer=naql_dot_v1_dot_services__pb2.InvoiceRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.InvoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naql.v1.FinTrackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naql.v1.FinTrackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinTrackService(object):
    """============================================================
    FinTrack Service
    ============================================================

    """

    @staticmethod
    def CreateQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/CreateQuote',
            naql_dot_v1_dot_services__pb2.CreateQuoteRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEscrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/CreateEscrow',
            naql_dot_v1_dot_services__pb2.CreateEscrowRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.EscrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseEscrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/ReleaseEscrow',
            naql_dot_v1_dot_services__pb2.ReleaseEscrowRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.EscrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/ProcessPayment',
            naql_dot_v1_dot_services__pb2.ProcessPaymentRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/GetBalance',
            naql_dot_v1_dot_services__pb2.GetBalanceRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/GetTransactionHistory',
            naql_dot_v1_dot_services__pb2.TransactionHistoryRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.TransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.FinTrackService/CreateInvoice',
            naql_dot_v1_dot_services__pb2.InvoiceRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.InvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """============================================================
    Agent Orchestrator
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/naql.v1.AgentService/Chat',
                request_serializer=naql_dot_v1_dot_services__pb2.ChatRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamChat = channel.unary_stream(
                '/naql.v1.AgentService/StreamChat',
                request_serializer=naql_dot_v1_dot_services__pb2.ChatRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ChatStreamChunk.FromString,
                _registered_method=True)
        self.GetConversationHistory = channel.unary_unary(
                '/naql.v1.AgentService/GetConversationHistory',
                request_serializer=naql_dot_v1_dot_services__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ConversationHistory.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/naql.v1.AgentService/ExecuteAction',
                request_serializer=naql_dot_v1_dot_services__pb2.ActionRequest.SerializeToString,
                response_deserializer=naql_dot_v1_dot_services__pb2.ActionResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """============================================================
    Agent Orchestrator
    ============================================================

    """

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversationHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ChatRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ChatResponse.SerializeToString,
            ),
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ChatRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ChatStreamChunk.SerializeToString,
            ),
            'GetConversationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversationHistory,
                    request_deserializer=naql_dot_v1_dot_services__pb2.GetHistoryRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ConversationHistory.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=naql_dot_v1_dot_services__pb2.ActionRequest.FromString,
                    response_serializer=naql_dot_v1_dot_services__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naql.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naql.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """============================================================
    Agent Orchestrator
    ============================================================

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.AgentService/Chat',
            naql_dot_v1_dot_services__pb2.ChatRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/naql.v1.AgentService/StreamChat',
            naql_dot_v1_dot_services__pb2.ChatRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ChatStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.AgentService/GetConversationHistory',
            naql_dot_v1_dot_services__pb2.GetHistoryRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ConversationHistory.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naql.v1.AgentService/ExecuteAction',
            naql_dot_v1_dot_services__pb2.ActionRequest.SerializeToString,
            naql_dot_v1_dot_services__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
